# Generated by Django 5.2 on 2025-05-03 15:06

import problems.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('status', models.CharField(blank=True, default='running', max_length=100, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, default=0, null=True)),
                ('memory', models.IntegerField(blank=True, default=0, null=True)),
                ('length', models.IntegerField(blank=True, default=0, null=True)),
                ('cases', models.JSONField(blank=True, default=list, null=True)),
                ('test', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('compiled', 'Compiled'), ('interpreted', 'Interpreted')], max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('sandbox', models.CharField(default='sandbox', max_length=100)),
                ('compile', models.CharField(blank=True, max_length=100, null=True)),
                ('run', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.JSONField(blank=True, default=dict, null=True)),
                ('hint', models.JSONField(blank=True, default=dict, null=True)),
                ('input', models.JSONField(blank=True, default=dict, null=True)),
                ('output', models.JSONField(blank=True, default=dict, null=True)),
                ('samples', models.JSONField(blank=True, default=list, null=True)),
                ('rank', models.IntegerField(default=800)),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], max_length=100)),
                ('time_limit', models.IntegerField(default=1)),
                ('memory_limit', models.IntegerField(default=64)),
                ('code_limit', models.IntegerField(default=10000)),
                ('output_limit', models.IntegerField(default=1000)),
                ('line_limit', models.IntegerField(default=1000)),
                ('language', models.CharField(max_length=10)),
                ('tests', models.FileField(blank=True, null=True, upload_to=problems.models.upload_to_tests)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('with_link', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
