# Generated by Django 5.2 on 2025-05-03 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attempt',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.language'),
        ),
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='problem_allowed_languages', to='problems.language'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problem_tags', to='problems.tag'),
        ),
        migrations.AddField(
            model_name='top',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_attempt_self', to='problems.attempt'),
        ),
        migrations.AddField(
            model_name='top',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_attempt_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='top',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_attempt_problem', to='problems.problem'),
        ),
    ]
