# Generated by Django 5.2 on 2025-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_bio_alter_user_city_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='premium_expires',
            field=models.DateTimeField(),
        ),
    ]
