# Generated by Django 5.2 on 2025-05-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_is_readed_session_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
